version: '3.9'

services:
  engine:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: syncadmin
      POSTGRES_PASSWORD: syncadmin
      POSTGRES_DB: syncdb
    ports:
      - "5432:5432"